module tb_mux_2x1();
	reg a,b,s;
	wire y;
	mux_2x1 dut (
		.a(a),
		.b(b),
		.s(s),
		.y(y)
	);
	initial begin
		$dumpfile("mux_2x1_waveform.vcd");
		$dumpvars(0,tb_mux_2x1);
		a=0;b=0;s=0;#10;
		a=1;b=0;s=0;#10;
		a=0;b=1;s=0;#10;
		a=1;b=1;s=0;#10;
		a=0;b=0;s=1;#10;
		a=1;b=0;s=1;#10;
		a=0;b=1;s=1;#10;
		a=1;b=1;s=1;#10;
		$finish;
	end
endmodule

			